name: registry-triggered
on:
  registry_package:
    types:
      - published
jobs:
  echo:
    if: ${{ github.event.registry_package.name == 'ghactions-playground/ghactions' }}
    runs-on: ubuntu-latest
    steps:
      - name: say something
        run: |
          echo running
