on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: bump version
        run: |
          make bump-version GITHUB_USER=${GITHUB_ACTOR} GITHUB_TOKEN=${{ secrets.TOKEN }} CONFIGURE_GIT=true
