on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: bump version
        run: |
          git config --global user.email "mail@makk.es"
          git config --global user.name "GitHub Actions Automation"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          TAG=$(git describe --tags --exact-match)
          echo ${TAG} > version
          git add version
          git commit -m "update version to ${TAG}"
          git push github HEAD:master
